### ISSUE TITLE
IsNuGetPublished for private repository

### ISSUE THREAD

**Issue by andreymir** [Redth/Cake.ExtendedNuGet#14]
When I call `IsNuGetPublished(package, feedSourceUrl)` where package is the path to a nuget package file and feedSourceUrl is ht eurl of the nuget repository, the command fails with the error `Error: An error occurred while loading packages from 'http://*******/nuget': The remote server returned an error: (401) Unauthorized.` Is there a place where I could specify username and password for our private nuget repository?

**Comment by AnnaMula** [comment]
Hi andreymir. Facing the sane issue here. Do you kindly have any workaround for this issue ?
Any input will be highly appreciated !

**Comment by andreymir** [comment]
@AnnaMula yes, I add this task int my build script
```
Task("Add private nuget feed")
	.Does(() =>
{
	var nugetSourceSettings = new NuGetSourcesSettings
	{
		UserName = "PRIVATE_FEED_USERNAME",
		Password = "NUGET.PRIVATE_FEED_PASSWORD",
		IsSensitiveSource = true
	};
	
	var feed = new
	{
		Name = "my_private_nuget_feed",
		Source = nugetFeedUrl
	};

	if (!NuGetHasSource(source: feed.Source))
	{
		Information("Private NuGet source missing. Add NuGet source.");

		NuGetAddSource(
			name: feed.Name,
			source: feed.Source,
			settings: nugetSourceSettings
		);
	}
	else
	{
		Information("Private NuGet source already exists");
	}
});
```

**Comment by AnnaMula** [comment]
Hi Andrey. Thx for the quick response.
Very appreciated 👍

**Comment by Redth** [comment]
Please try the latest version.
