### ISSUE TITLE
Cake 0.20.0

### ISSUE THREAD

**Issue by skovsende** [Redth/Cake.ExtendedNuGet#15]
It looks like the latest version of Cake broke this addin. When I run a simple cake script(https://gist.github.com/skovsende/9279e0ca8baa29ceb1330797103ba252), it fails with:
Error: Object reference not set to an instance of an object.

I have tried to update the Cake references in Cake.ExtendedNuGet to Cake 0.20.0 packages, but that does not seem to be enough.

**Comment by liri2006** [comment]
+1, faced same issue.

**Comment by skovsende** [comment]
After looking into the problem it seems to be a problem related to using an old version of Roslyn. If cake is run with the --experimental flag, it runs fine. Cake is set to upgrade to a newer version of Roslyn in 0.22.0, so my hope is that this will fix the problem. https://github.com/cake-build/cake/issues/1540

**Comment by CharliePoole** [comment]
Why do you need the extended nuget addin? Why won't just installing the addins in a work directory like I did work for us?

**Comment by OskarKlintrot** [comment]
I think it's time for an upgrade now, Cake just released 0.22 and this addin can no longer be installed with 0.22.

**Comment by skovsende** [comment]
I have created #22 that updates to use Cake 0.22.0

**Comment by skovsende** [comment]
#21 has just been merged, so with a little luck we should soon have a version of the addin supporting 0.22.x.

**Comment by skovsende** [comment]
1.0.0.27 has been released and fixes this issue.
