### ISSUE TITLE
Symbols packages are not pushed

### ISSUE THREAD

**Issue by wojciechrak** [Redth/Cake.ExtendedNuGet#25]
Symbols packages are not published, because related main package is already published.

I am using a Klondike nuget server (https://github.com/themotleyfool/Klondike), which has the same endpoint for symbol packages, as for regular packages. There is no problem when using `nuget.exe` to push packages, server handles this well. 

However this addin gets Package ID from .nupkg file, and assumes that it was already pushed.

```
11:42:24 Pushing My.Package.1.0.2-b24.nupkg to 'http://mynugetsource.com/api/odata'...
11:42:24   PUT http://mynugetsource.com/api/odata/
11:42:24   Created http://mynugetsource.com/api/odata/ 456ms
11:42:24 Your package was pushed.
11:42:24 Published Package successfully: C:/dev/jenkins-swarm/workspace/workspace/BUILD/source/My.Package/bin/Release/My.Package.1.0.2-b24.nupkg
11:42:25 Already published: C:/dev/jenkins-swarm/workspace/workspace/BUILD/source/My.Package/bin/Release/My.Package.1.0.2-b24.symbols.nupkg
```

**Comment by Redth** [comment]
We should probably deprecate the publish methods here.  They are really no longer necessary as nuget.exe itself has support for skipping existing packages without failing.
