### ISSUE TITLE
Publish latest source to nuget

### ISSUE THREAD

**Issue by DanFTRX** [Redth/Cake.ExtendedNuGet#31]
The latest nuget package for this addin is not compatible with newer cake core versions.  I see you have already made the changes neccessary, but not deployed them.

**Comment by DemoBytom** [comment]
Is this going to be uploaded to NuGet? I see a release was made 2 days ago, but it doesn't seem to be available on NuGet.org?

**Comment by Redth** [comment]
Yep working on it.
