### ISSUE TITLE
Feature aliases for handling package.config

### ISSUE THREAD

**Issue by robgha01** [Redth/Cake.ExtendedNuGet#8]
https://gist.github.com/robgha01/52067e2ba48e7877ab844dab9fca2a31

Some useful aliases to get PackageReference/PackageReferences etc.

**Comment by robgha01** [comment]
#9 Created a pull request.

**Comment by robgha01** [comment]
@Redth It seam to throw this error https://gist.github.com/robgha01/c49498f62c46caa8c553f1f51b6f506b
as it could not find a reference to the NuGet.Core is that bundled with this package ?

if not we either need to bundle it or update the how to use this "Cake.ExtendedNuGet" with the following:
```
#addin "NuGet.Core"
#addin "Cake.ExtendedNuGet"
```

**Comment by Redth** [comment]
We should update the readme

**Comment by robgha01** [comment]
@Redth i think its also good to update the NuGet.Core to the latest version i'm struggling to get this to work getting many strange errors about dll versions. https://gist.github.com/robgha01/41ecbbf357288cffeff00168f3e7a691

**Comment by robgha01** [comment]
@Redth it is looking for "Cake.ExtendedNuGet, Version=1.0.6104.34637" but the version i know of dont go up that high i used this
```
#addin "nuget:?package=NuGet.Core&version=2.8.6"
#addin "Cake.ExtendedNuGet"
//#addin "nuget:?package=Cake.ExtendedNuGet&version=1.0.0.22"
```

i get this when i call any method ex:
Task("Test")
    .Does(() =>
{
	IsNuGetPublished("NuGet.Core", "2.12.0");
});

**Comment by robgha01** [comment]
ziped the whole build script start it by opening StartDebug.bat its included in the visual studio project or located in Build/ folder.
https://drive.google.com/file/d/0B1HsJ07Q3udPUTZtN2NyYVN1Q0E/view?usp=sharing

**Comment by gep13** [comment]
@robgha01 @Redth so, from what I can see, things seem to be working as expected....

https://gitter.im/cake-build/cake?at=57de9b9418291e10487fac5b

Let me know if I have missed something.

**Comment by robgha01** [comment]
@gep13 @Redth 
i still cant make it to work when i call it as it should be called with the correct parameters the others you looked on was only small tests of mine.

this is the code i tested with its reflection and its the only way to make it work at least the only way i know of...

```
Task("Test")
    .Does(() =>
{
	var srcPath = new DirectoryPath("../BlueLeet.Build/");
	var type = typeof(Cake.ExtendedNuGet.ExtendedNuGetAliases);	
	MethodInfo GetPackageReferencesInfo = typeof(Cake.ExtendedNuGet.ExtendedNuGetAliases).GetMethod("GetPackageReferences", BindingFlags.Public | BindingFlags.Static);
	var result = GetPackageReferencesInfo.Invoke(null, new[]{null, srcPath}) as IEnumerable<dynamic>;

	foreach(var p in result)
	{
		Information("Package:'{0}'", p.ToString());
		Information("PackageID:'{0}'", p.Id);
		Information("PackageVersion:'{0}'", p.Version.ToString());
	}

    //var treferen = GetPackageReferences(new DirectoryPath("../BlueLeet.Build/"));
});
```

**Comment by robgha01** [comment]
@gep13 @Redth ok, new findings "System.MissingMethodException: Metoden hittades inte: NuGet.SemanticVersion Cake.ExtendedNuGet.PackageReferenceEntity.get_Version()."

I created a entity class ex:
`public class PackageReferenceEntity : IEquatable<PackageReferenceEntity>
    {
        public string Id { get; private set; }

        public SemanticVersion Version { get; private set; }

        public IVersionSpec VersionConstraint { get; set; }

        public FrameworkName TargetFramework { get; private set; }

        public bool IsDevelopmentDependency { get; private set; }

        public bool RequireReinstallation { get; private set; }

        public PackageReferenceEntity(PackageReference reference)
        {
            Id = reference.Id;
            Version = reference.Version;
            VersionConstraint = reference.VersionConstraint;
            TargetFramework = reference.TargetFramework;
            IsDevelopmentDependency = reference.IsDevelopmentDependency;
            RequireReinstallation = reference.RequireReinstallation;
        }

        public override bool Equals(object obj)
        {
            PackageReferenceEntity other = obj as PackageReferenceEntity;
            if (other != null)
            {
                return Equals(other);
            }

            return false;
        }

        public override int GetHashCode()
        {
            return Id.GetHashCode() * 3137 + (Version == null ? 0 : Version.GetHashCode());
        }

        public override string ToString()
        {
            if (Version == null)
            {
                return Id;
            }

            if (VersionConstraint == null)
            {
                return Id + " " + Version;
            }

            return Id + " " + Version + " (" + VersionConstraint + ")";
        }

        public bool Equals(PackageReferenceEntity other)
        {
            if (other == null)
            {
                return false;
            }

            if (Id.Equals(other.Id, StringComparison.OrdinalIgnoreCase))
            {
                return Version == other.Version;
            }

            return false;
        }
    }`
And changed both of the return types to this class.
then i ran the the cake program and got the above exception so it seams that for some reason it can not find SemanticVersion that is a part of NuGet.Core anyone know way xD at least we have found the culprit... and the previous missing method exception must have pointed to this exception i think but in a cryptic none helping way. so if i change the entity to string and do a .ToString() on the SemanticVersion it all works ... but it would really be nice if this "hack" of implementation would not be necessary which leads me to the next question how to tackle this xD

**Comment by robgha01** [comment]
@gep13 @Redth ok, i think this is an acceptable solution i don't know way the semantik version property wont work but this small hack of doing it to a string is working however way in the forsaken lands of programming is this working
`var t = new NuGet.SemanticVersion(p.Version);
Information("PackageVersion:'{0}'", t);`

Created a new pull request. https://github.com/Redth/Cake.ExtendedNuGet/pull/10

**Comment by Redth** [comment]
Think we're good in the latest version?
